export const catchingErrors = (error) => {
    return alert(error)
}